# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
      name: self-hosted
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'AzureAssignment'
        regionName: 'ap-south-1'
        imageSource: 'imagename'
        sourceImageName: 'flask-app'
        repositoryName: 'azureassignmentecr'