# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
      name: self-hosted
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'liquiDocker'
        command: 'login'

    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'liquiDocker'
        repository: 'liquizar/simple-flask-app'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'

    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'AzureAssignment'
        regionName: 'ap-south-1'
        imageSource: 'imagename'
        sourceImageName: 'flask-app'
        repositoryName: 'azureassignmentecr'